# Generated by Django 6.0.2 on 2026-02-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
