# Generated by Django 6.0.2 on 2026-02-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0004_myappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointment',
            old_name='detatime',
            new_name='datetime',
        ),
    ]
